version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    #image: dyegocantusoftfocus/app
    depends_on:
      - db
    ports:
      - "8000:8000"
