version: '3'
services:

  app:
    build:
      dockerfile: "Dockerfile"
      context: "."
    image: "dyegocantusoftfocus/app"
    container_name: "app"
    ports:
      - "8000:8000"
    networks:
      - "app-network"
    depends_on:
      - "db"

  db:
    image: "postgres"
    hostname: "db"
    container_name: "db"
    environment:
      - "POSTGRES_USER=app"
      - "POSTGRES_PASSWORD=app"
    networks:
      - "app-network"

networks: 
    app-network:
        driver: bridge
