version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    depends_on:
      - db
