version: '3'
services:
  db:
    image: postgres:10.4-alpine
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    depends_on:
      - db
